# Generated by Django 4.1.7 on 2023-05-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Myimages2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Myimages',
        ),
    ]
