# Generated by Django 4.1.7 on 2023-05-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_images', '0003_myimages_delete_myimages2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Myimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='Myimages',
        ),
    ]
