# Generated by Django 4.1.7 on 2023-05-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_images', '0004_myimage_delete_myimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Myimages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Users_table',
            fields=[
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('college', models.CharField(max_length=255)),
                ('course', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('gender', models.CharField(max_length=255)),
                ('images', models.ImageField(upload_to='images')),
                ('phone', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Myimage',
        ),
    ]
