# Generated by Django 4.1.7 on 2023-05-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_images', '0005_myimages_users_table_delete_myimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Myimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('imgurl', models.CharField(max_length=500)),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Myimages',
        ),
        migrations.DeleteModel(
            name='Users_table',
        ),
    ]
